/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade05.view;

/**
 *
 * @author sunhe
 */
import javax.swing.DefaultListModel;
public class RepetiçãoComSlider extends javax.swing.JFrame {

    /**
     * Creates new form RepetiçãoComSlider
     */
    public RepetiçãoComSlider() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMsgInicio = new javax.swing.JLabel();
        sliderInicio = new javax.swing.JSlider();
        lblMsgFim = new javax.swing.JLabel();
        sliderFim = new javax.swing.JSlider();
        lblMsgPasso = new javax.swing.JLabel();
        sliderPasso = new javax.swing.JSlider();
        btnContar = new javax.swing.JButton();
        lblNumInicio = new javax.swing.JLabel();
        lblNumFim = new javax.swing.JLabel();
        lblNumPasso = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaNumeros = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMsgInicio.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        lblMsgInicio.setText("INíCIO");
        getContentPane().add(lblMsgInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 39, 43, -1));

        sliderInicio.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        sliderInicio.setMaximum(10);
        sliderInicio.setValue(0);
        sliderInicio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderInicioStateChanged(evt);
            }
        });
        getContentPane().add(sliderInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 40, 140, -1));

        lblMsgFim.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        lblMsgFim.setText("FIM");
        getContentPane().add(lblMsgFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 66, 45, -1));

        sliderFim.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        sliderFim.setMaximum(20);
        sliderFim.setMinimum(1);
        sliderFim.setToolTipText("");
        sliderFim.setValue(1);
        sliderFim.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderFimStateChanged(evt);
            }
        });
        getContentPane().add(sliderFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 66, 140, -1));

        lblMsgPasso.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        lblMsgPasso.setText("PASSO");
        getContentPane().add(lblMsgPasso, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 93, 45, -1));

        sliderPasso.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        sliderPasso.setMaximum(5);
        sliderPasso.setMinimum(1);
        sliderPasso.setValue(1);
        sliderPasso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderPassoStateChanged(evt);
            }
        });
        getContentPane().add(sliderPasso, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 93, 140, -1));

        btnContar.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        btnContar.setForeground(new java.awt.Color(255, 0, 51));
        btnContar.setText("CONTAR");
        btnContar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContarActionPerformed(evt);
            }
        });
        getContentPane().add(btnContar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        lblNumInicio.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        lblNumInicio.setText("0");
        getContentPane().add(lblNumInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 20, -1));

        lblNumFim.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        lblNumFim.setText("1");
        getContentPane().add(lblNumFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 20, -1));

        lblNumPasso.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        lblNumPasso.setText("1");
        getContentPane().add(lblNumPasso, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 20, -1));

        listaNumeros.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        listaNumeros.setForeground(new java.awt.Color(153, 153, 255));
        jScrollPane1.setViewportView(listaNumeros);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 120, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Método para contar os valores
    private void btnContarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContarActionPerformed
        // TODO add your handling code here:
        int valInicio = sliderInicio.getValue();
        int valFim = sliderFim.getValue();
        int valPasso = sliderPasso.getValue();
        
        DefaultListModel lista = new DefaultListModel(); 
        
        for(int a = valInicio; a <= valFim; a += valPasso){
            lista.addElement(a);
        }
        
        listaNumeros.setModel(lista);
    }//GEN-LAST:event_btnContarActionPerformed

    //Método para mostrar o valor do slider inicio sendo alterado.
    private void sliderInicioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderInicioStateChanged
        // TODO add your handling code here:
        int valor = sliderInicio.getValue();//Pegando o valor do slider
        lblNumInicio.setText(Integer.toString(valor));//Mostrando o valor no label
    }//GEN-LAST:event_sliderInicioStateChanged

    //Método para mostrar o valor do slider fim sendo alterado.
    private void sliderFimStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderFimStateChanged
        // TODO add your handling code here:
        int valor = sliderFim.getValue();//Pegando o valor do slider
        lblNumFim.setText(Integer.toString(valor));//Mostrando o valor no label
    }//GEN-LAST:event_sliderFimStateChanged

    //Método para mostrar o valor do slider passo sendo alterado.
    private void sliderPassoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderPassoStateChanged
        // TODO add your handling code here:
        int valor = sliderPasso.getValue();//Pegando o valor do slider
        lblNumPasso.setText(Integer.toString(valor));//Mostrando o valor no label
    }//GEN-LAST:event_sliderPassoStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RepetiçãoComSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RepetiçãoComSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RepetiçãoComSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RepetiçãoComSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RepetiçãoComSlider().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMsgFim;
    private javax.swing.JLabel lblMsgInicio;
    private javax.swing.JLabel lblMsgPasso;
    private javax.swing.JLabel lblNumFim;
    private javax.swing.JLabel lblNumInicio;
    private javax.swing.JLabel lblNumPasso;
    private javax.swing.JList<String> listaNumeros;
    private javax.swing.JSlider sliderFim;
    private javax.swing.JSlider sliderInicio;
    private javax.swing.JSlider sliderPasso;
    // End of variables declaration//GEN-END:variables
}
